In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
df1 = pd.read_csv(r'C:\Users\junhyun111\Desktop\mf\outputs\psa_synthetic_dataset.csv')
df2 = pd.read_csv(r'C:\Users\junhyun111\Desktop\mf\outputs\psa_synthetic_dataset_2.csv')

In [4]:
df = pd.concat([df1,df2], axis = 0, ignore_index = True)
del df["sample_id"]

In [6]:
df.head()        # 상위 5개

,P_ads,P_des,t_ads,t_des,t_purge,u,qmax,b,k_LDF,L,...,productivity,energy_proxy,q_avg,q_final_avg,outlet_ads_final,outlet_dep_final,outlet_des_avg,outlet_rep_final,final_loading_mean,final_loading_max
0,6.054951,0.873666,62.054466,115.813491,28.011856,0.069012,5.464195,0.649083,0.193081,1.818575,...,0.048123,8.228701,0.140042,0.140042,1.089651e-02,0.015197,0.075608,1.456699e-02,0.140042,1.770346
1,7.031458,0.412761,48.206119,142.540075,98.409138,0.125953,3.469961,0.240488,0.151855,1.220017,...,0.014605,18.952628,0.221624,0.221624,1.002538e-01,0.176072,0.018761,1.952961e-03,0.221624,0.659784
2,4.808193,0.855971,81.967146,155.970574,74.938856,0.065234,5.212205,1.063644,0.199437,0.551882,...,0.045940,7.551639,0.185833,0.185833,1.909728e-07,0.000021,0.066229,1.353652e-06,0.185833,2.142806
3,7.590316,0.135430,167.840648,167.638461,41.264146,0.144445,2.995455,1.077786,0.091693,1.366215,...,0.052355,57.928635,0.187889,0.187889,1.107769e-01,0.231149,0.099461,2.922417e-08,0.187889,1.342789
4,7.770291,0.499423,56.268168,149.037565,29.534695,0.124922,5.848057,0.491532,0.061796,1.598276,...,0.044674,17.196600,0.173463,0.173463,1.721404e-04,0.005095,0.063764,1.292825e-04,0.173463,1.422249

In [7]:
df.info()        # 데이터 타입, 결측치

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 25 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   P_ads               300 non-null    float64
 1   P_des               300 non-null    float64
 2   t_ads               300 non-null    float64
 3   t_des               300 non-null    float64
 4   t_purge             300 non-null    float64
 5   u                   300 non-null    float64
 6   qmax                300 non-null    float64
 7   b                   300 non-null    float64
 8   k_LDF               300 non-null    float64
 9   L                   300 non-null    float64
 10  eps                 300 non-null    float64
 11  t_repress           300 non-null    float64
 12  cycle               300 non-null    float64
 13  purity              300 non-null    float64
 14  recovery            300 non-null    float64
 15  productivity        300 non-null    float64
 16  energy_proxy        300 non-null    float64
 17  q_avg               300 non-null    float64
 18  q_final_avg         300 non-null    float64
 19  outlet_ads_final    300 non-null    float64
 20  outlet_dep_final    300 non-null    float64
 21  outlet_des_avg      300 non-null    float64
 22  outlet_rep_final    300 non-null    float64
 23  final_loading_mean  300 non-null    float64
 24  final_loading_max   300 non-null    float64
dtypes: float64(25)
memory usage: 58.7 KB

In [8]:
df.describe()    # 통계 요약

,P_ads,P_des,t_ads,t_des,t_purge,u,qmax,b,k_LDF,L,...,productivity,energy_proxy,q_avg,q_final_avg,outlet_ads_final,outlet_dep_final,outlet_des_avg,outlet_rep_final,final_loading_mean,final_loading_max
count,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,300.000000,...,300.000000,300.000000,300.000000,300.000000,3.000000e+02,3.000000e+02,300.000000,3.000000e+02,300.000000,300.000000
mean,4.999391,0.524871,115.006350,114.983944,55.015288,0.084991,4.000315,0.850277,0.110000,1.249705,...,0.046865,16.763203,0.196781,0.196781,5.301613e-02,8.876242e-02,0.092726,1.011100e-02,0.196781,1.083521
std,1.734658,0.274530,49.150215,49.171093,26.024677,0.037578,1.156394,0.376063,0.052034,0.433696,...,0.020616,15.735833,0.141649,0.141649,5.830235e-02,7.973723e-02,0.056442,3.150373e-02,0.141649,0.542781
min,2.024370,0.053501,30.140439,30.771688,10.194797,0.020242,2.011153,0.201788,0.020047,0.504165,...,0.002545,3.269167,0.023120,0.023120,1.824207e-08,1.598698e-07,0.004914,2.553999e-14,0.023120,0.168365
25%,3.512521,0.286950,72.522325,72.478271,32.724951,0.052929,3.008303,0.524976,0.065033,0.875838,...,0.031654,7.664548,0.106320,0.106320,2.137621e-03,8.319509e-03,0.050266,2.449066e-05,0.106320,0.683371
50%,5.006131,0.524070,115.182757,115.289232,55.114166,0.084987,3.997180,0.850870,0.110092,1.252079,...,0.046230,10.977352,0.165107,0.165107,2.319464e-02,7.103679e-02,0.082361,1.559200e-03,0.165107,1.010735
75%,6.495548,0.761638,157.375771,157.041762,77.563763,0.117254,4.987946,1.174257,0.154660,1.622724,...,0.061550,19.424330,0.242035,0.242035,1.165973e-01,1.604168e-01,0.123494,9.765343e-03,0.242035,1.395959
max,7.986042,0.995561,199.597941,199.777464,99.966266,0.149514,5.993031,1.498296,0.199437,1.995537,...,0.093818,103.906591,1.176452,1.176452,1.500000e-01,2.626604e-01,0.342978,4.808620e-01,1.176452,2.938755

In [9]:
df.columns       # 컬럼명 확인

Index(['P_ads', 'P_des', 't_ads', 't_des', 't_purge', 'u', 'qmax', 'b',
       'k_LDF', 'L', 'eps', 't_repress', 'cycle', 'purity', 'recovery',
       'productivity', 'energy_proxy', 'q_avg', 'q_final_avg',
       'outlet_ads_final', 'outlet_dep_final', 'outlet_des_avg',
       'outlet_rep_final', 'final_loading_mean', 'final_loading_max'],
      dtype='object')

In [10]:
df.to_csv("output.csv")